# Generated by Django 5.2.14 on 2026-06-01 22:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_returns_from_sales(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    SaleItem = apps.get_model("sales", "SaleItem")
    SaleReturn = apps.get_model("sales", "SaleReturn")
    SaleReturnItem = apps.get_model("sales", "SaleReturnItem")

    for sale in Sale.objects.filter(is_return=True).iterator():
        sale_return = SaleReturn.objects.create(
            id=sale.id,
            client_id=sale.client_id,
            tenant_id=sale.tenant_id,
            user_id=sale.user_id,
            shift_id=sale.shift_id,
            customer_id=sale.customer_id,
            customer_name=sale.customer_name,
            status=sale.status,
            payment_type=sale.payment_type,
            subtotal=sale.subtotal,
            discount_amount=sale.discount_amount,
            total=sale.total,
            paid_amount=sale.paid_amount,
            debt_amount=sale.debt_amount,
            comment=sale.comment,
            receipt_number=sale.receipt_number,
            created_at=sale.created_at,
            completed_at=sale.completed_at,
            synced_at=sale.synced_at,
        )
        for item in SaleItem.objects.filter(sale_id=sale.id):
            SaleReturnItem.objects.create(
                id=item.id,
                sale_return_id=sale_return.id,
                product_id=item.product_id,
                product_name=item.product_name,
                quantity=item.quantity,
                unit_price=item.unit_price,
                discount=item.discount,
                total=item.total,
            )


def delete_legacy_return_sales(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    Sale.objects.filter(is_return=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_groups_alter_user_is_active_and_more"),
        ("catalog", "0004_unitofmeasure_product_unit_ref"),
        ("sales", "0003_sale_is_return"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("completed", "Yakunlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta"),
                            ("mixed", "Aralash"),
                            ("credit", "Qarzga"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("debt_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("comment", models.TextField(blank=True)),
                ("receipt_number", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="sales.customer",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.shift",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Qaytarish",
                "verbose_name_plural": "Qaytarishlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=300)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salereturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qaytarish mahsuloti",
                "verbose_name_plural": "Qaytarish mahsulotlari",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(migrate_returns_from_sales, migrations.RunPython.noop),
        migrations.RunPython(delete_legacy_return_sales, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sale",
            name="is_return",
        ),
    ]
