# Generated by Django 5.2.14 on 2026-07-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_debt_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='salereturnitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Qaytarish mahsuloti', 'verbose_name_plural': 'Qaytarish mahsulotlari'},
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
