# Generated by Django 5.2.14 on 2026-08-08 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_fifo_stock_batches'),
        ('sales', '0007_sale_cash_ledger_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sotuv partiya sarfi',
                'verbose_name_plural': 'Sotuv partiya sarflari',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItemBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Qaytarish partiya bog'lanishi",
                'verbose_name_plural': "Qaytarish partiya bog'lanishlari",
            },
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_tenant__fc19fe_idx',
            old_name='sales_sale_tenant_status_comp_idx',
        ),
        migrations.AddField(
            model_name='saleitembatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='catalog.stockbatch'),
        ),
        migrations.AddField(
            model_name='saleitembatch',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='salereturnitembatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_allocations', to='catalog.stockbatch'),
        ),
        migrations.AddField(
            model_name='salereturnitembatch',
            name='return_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.salereturnitem'),
        ),
    ]
