# Generated by Django 5.2.14 on 2026-05-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productbarcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productbarcode',
            new_name='catalog_pro_tenant__36f517_idx',
            old_name='catalog_pro_tenant__bc_idx',
        ),
    ]
