# Generated by Django 5.2.14 on 2026-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_stockaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='is_selling',
            field=models.BooleanField(default=False, help_text='Mahsulotning asosiy sotuv narxi (product.price)'),
        ),
    ]
