# Generated by Django 5.2.14 on 2026-08-08 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_cashierproductfavorite'),
        ('catalog', '0012_product_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.PositiveIntegerField(db_index=True)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('qty_remaining', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('source_type', models.CharField(choices=[('opening', "Boshlang'ich"), ('receipt', 'Kirim'), ('return', 'Qaytarish'), ('audit', 'Reviziya'), ('adjustment', 'Tuzatish')], default='receipt', max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ombor partiyasi',
                'verbose_name_plural': 'Ombor partiyalari',
                'ordering': ['received_at', 'batch_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('opening', "Boshlang'ich"), ('receipt', 'Kirim'), ('sale', 'Sotuv'), ('return', 'Qaytarish'), ('sale_cancel', 'Sotuv bekor'), ('return_cancel', 'Qaytarish bekor'), ('audit', 'Reviziya'), ('adjustment', 'Tuzatish')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_tenant__e1f8c5_idx',
            old_name='catalog_pro_tenant__is_act_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_tenant__f39444_idx',
            old_name='catalog_pro_tenant__upd_at_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_tenant__48a14c_idx',
            old_name='catalog_pro_tenant__categ_idx',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='receipt_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='catalog.stockreceiptitem'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='catalog.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.tenant'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['tenant', 'product', 'received_at'], name='catalog_sto_tenant__be95ab_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'qty_remaining'], name='catalog_sto_product_ec25a7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'product', '-created_at'], name='catalog_sto_tenant__b11210_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='catalog_sto_referen_cf2259_idx'),
        ),
    ]
